name: test pnpm#4961

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '*.md'

  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.4.1

      - name: Install dependencies
        run: pnpm install

      - name: Run
        run: pnpm start
